---
name: Sync main to preview
on:
  push:
    branches:
      - main
jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.ECOSPARK_APP_ID }}
          private_key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: preview
          token: ${{ steps.generate-token.outputs.token }}
          force: true
